#!/usr/bin/env python3
"""List available traces in a data directory.

Discovers traces from .meta.json sidecar files (generated by generate.py)
and from bare load_*/run_* file pairs (backward compatibility with traces
generated before the metadata system existed).

Usage:
  python3 traces/list.py [data-dir]          # default: /mnt/ssd/ycsb_data
  python3 traces/list.py /mnt/ssd/ycsb_data --json
"""

import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from generators.base import TraceMetadata


def _discover_meta(data_dir: str) -> list[TraceMetadata]:
    """Find all .meta.json files."""
    metas = []
    for f in sorted(os.listdir(data_dir)):
        if f.endswith(".meta.json"):
            try:
                metas.append(TraceMetadata.load(os.path.join(data_dir, f)))
            except Exception as e:
                print(f"  WARN: skipping {f}: {e}", file=sys.stderr)
    return metas


def _discover_bare(data_dir: str, known_load_files: set[str]) -> list[TraceMetadata]:
    """Find load_*/run_* pairs that lack .meta.json."""
    load_files = {}
    run_files = {}
    for f in sorted(os.listdir(data_dir)):
        path = os.path.join(data_dir, f)
        if not os.path.isfile(path) or not f.endswith("_raw.dat"):
            continue
        if f.startswith("load_"):
            # Extract name: load_<name>_<count>_raw.dat -> name
            m = re.match(r"load_(.+?)_\d+[GMK]?_raw\.dat$", f)
            if m:
                load_files[m.group(1)] = path
        elif f.startswith("run_"):
            m = re.match(r"run_(.+?)_\d+[GMK]?_\d+[GMK]?_raw\.dat$", f)
            if m:
                run_files[m.group(1)] = path

    bare = []
    for name in sorted(set(load_files) & set(run_files)):
        lf = load_files[name]
        rf = run_files[name]
        if os.path.abspath(lf) in known_load_files:
            continue  # already covered by .meta.json
        lc = os.path.getsize(lf) // 8
        rc = os.path.getsize(rf) // 8
        bare.append(TraceMetadata(
            name=name, category="(unknown)", generator="(legacy)",
            description=f"Discovered from file pair",
            load_file=os.path.abspath(lf), run_file=os.path.abspath(rf),
            load_count=lc, run_count=rc,
        ))
    return bare


def main():
    parser = argparse.ArgumentParser(description="List available traces.")
    parser.add_argument("data_dir", nargs="?", default="/mnt/ssd/ycsb_data",
                        help="Directory containing trace files (default: /mnt/ssd/ycsb_data)")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()

    if not os.path.isdir(args.data_dir):
        print(f"ERROR: {args.data_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    metas = _discover_meta(args.data_dir)
    known_loads = {m.load_file for m in metas}
    bare = _discover_bare(args.data_dir, known_loads)
    all_traces = metas + bare

    if not all_traces:
        print(f"No traces found in {args.data_dir}")
        print(f"Generate with: python3 traces/generate.py zipf --outdir {args.data_dir}")
        return

    if args.json:
        from dataclasses import asdict
        print(json.dumps([asdict(m) for m in all_traces], indent=2))
        return

    # Formatted table grouped by category
    by_cat: dict[str, list[TraceMetadata]] = {}
    for m in all_traces:
        by_cat.setdefault(m.category, []).append(m)

    header = f"{'Name':<28} {'Load Keys':>14} {'Run Keys':>14} {'Size':>8} {'Description'}"
    sep = "-" * len(header)

    for cat in sorted(by_cat):
        print(f"\n  [{cat}]")
        print(f"  {header}")
        print(f"  {sep}")
        for m in by_cat[cat]:
            load_gb = os.path.getsize(m.load_file) / 1e9 if os.path.exists(m.load_file) else 0
            run_gb = os.path.getsize(m.run_file) / 1e9 if os.path.exists(m.run_file) else 0
            total_gb = load_gb + run_gb
            print(f"  {m.name:<28} {m.load_count:>14,} {m.run_count:>14,} "
                  f"{total_gb:>6.1f}GB  {m.description}")

    print(f"\n  Total: {len(all_traces)} traces in {args.data_dir}")


if __name__ == "__main__":
    main()
